//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from VoxScript2.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="VoxScriptParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IVoxScriptVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] VoxScriptParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] VoxScriptParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] VoxScriptParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.print"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrint([NotNull] VoxScriptParser.PrintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.var_define"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVar_define([NotNull] VoxScriptParser.Var_defineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.val_assign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVal_assign([NotNull] VoxScriptParser.Val_assignContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.arith_assign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArith_assign([NotNull] VoxScriptParser.Arith_assignContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.val_increment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVal_increment([NotNull] VoxScriptParser.Val_incrementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.func_define"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunc_define([NotNull] VoxScriptParser.Func_defineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.func_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunc_call([NotNull] VoxScriptParser.Func_callContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.cont_while"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCont_while([NotNull] VoxScriptParser.Cont_whileContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.cont_for"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCont_for([NotNull] VoxScriptParser.Cont_forContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.cont_foreach"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCont_foreach([NotNull] VoxScriptParser.Cont_foreachContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.cont_return"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCont_return([NotNull] VoxScriptParser.Cont_returnContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.cont_continue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCont_continue([NotNull] VoxScriptParser.Cont_continueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.cont_break"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCont_break([NotNull] VoxScriptParser.Cont_breakContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.cont_if"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCont_if([NotNull] VoxScriptParser.Cont_ifContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.cont_else"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCont_else([NotNull] VoxScriptParser.Cont_elseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.type_annotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_annotation([NotNull] VoxScriptParser.Type_annotationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] VoxScriptParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.table_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTable_definition([NotNull] VoxScriptParser.Table_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.table_member_dict"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTable_member_dict([NotNull] VoxScriptParser.Table_member_dictContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.table_member_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTable_member_list([NotNull] VoxScriptParser.Table_member_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.table_member"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTable_member([NotNull] VoxScriptParser.Table_memberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.table_key"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTable_key([NotNull] VoxScriptParser.Table_keyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.lambda"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambda([NotNull] VoxScriptParser.LambdaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier([NotNull] VoxScriptParser.IdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.postfix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPostfix([NotNull] VoxScriptParser.PostfixContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.id_postfix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitId_postfix([NotNull] VoxScriptParser.Id_postfixContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.expression_postfix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression_postfix([NotNull] VoxScriptParser.Expression_postfixContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.function_postfix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_postfix([NotNull] VoxScriptParser.Function_postfixContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.function_params"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_params([NotNull] VoxScriptParser.Function_paramsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.var_inst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVar_inst([NotNull] VoxScriptParser.Var_instContext context);
}
