//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from VoxScript.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IVoxScriptListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class VoxScriptBaseListener : IVoxScriptListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] VoxScriptParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] VoxScriptParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] VoxScriptParser.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] VoxScriptParser.BlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] VoxScriptParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] VoxScriptParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.print"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrint([NotNull] VoxScriptParser.PrintContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.print"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrint([NotNull] VoxScriptParser.PrintContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.var_define"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVar_define([NotNull] VoxScriptParser.Var_defineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.var_define"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVar_define([NotNull] VoxScriptParser.Var_defineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.val_assign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVal_assign([NotNull] VoxScriptParser.Val_assignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.val_assign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVal_assign([NotNull] VoxScriptParser.Val_assignContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.arith_assign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArith_assign([NotNull] VoxScriptParser.Arith_assignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.arith_assign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArith_assign([NotNull] VoxScriptParser.Arith_assignContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.val_increment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVal_increment([NotNull] VoxScriptParser.Val_incrementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.val_increment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVal_increment([NotNull] VoxScriptParser.Val_incrementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.func_define"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunc_define([NotNull] VoxScriptParser.Func_defineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.func_define"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunc_define([NotNull] VoxScriptParser.Func_defineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.func_call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunc_call([NotNull] VoxScriptParser.Func_callContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.func_call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunc_call([NotNull] VoxScriptParser.Func_callContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.cont_while"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCont_while([NotNull] VoxScriptParser.Cont_whileContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.cont_while"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCont_while([NotNull] VoxScriptParser.Cont_whileContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.cont_for"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCont_for([NotNull] VoxScriptParser.Cont_forContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.cont_for"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCont_for([NotNull] VoxScriptParser.Cont_forContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.cont_foreach"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCont_foreach([NotNull] VoxScriptParser.Cont_foreachContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.cont_foreach"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCont_foreach([NotNull] VoxScriptParser.Cont_foreachContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.cont_return"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCont_return([NotNull] VoxScriptParser.Cont_returnContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.cont_return"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCont_return([NotNull] VoxScriptParser.Cont_returnContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.cont_continue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCont_continue([NotNull] VoxScriptParser.Cont_continueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.cont_continue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCont_continue([NotNull] VoxScriptParser.Cont_continueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.cont_break"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCont_break([NotNull] VoxScriptParser.Cont_breakContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.cont_break"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCont_break([NotNull] VoxScriptParser.Cont_breakContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.cont_if"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCont_if([NotNull] VoxScriptParser.Cont_ifContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.cont_if"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCont_if([NotNull] VoxScriptParser.Cont_ifContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.cont_else"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCont_else([NotNull] VoxScriptParser.Cont_elseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.cont_else"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCont_else([NotNull] VoxScriptParser.Cont_elseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.type_annotation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType_annotation([NotNull] VoxScriptParser.Type_annotationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.type_annotation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType_annotation([NotNull] VoxScriptParser.Type_annotationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] VoxScriptParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] VoxScriptParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.table_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTable_definition([NotNull] VoxScriptParser.Table_definitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.table_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTable_definition([NotNull] VoxScriptParser.Table_definitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.table_member_dict"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTable_member_dict([NotNull] VoxScriptParser.Table_member_dictContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.table_member_dict"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTable_member_dict([NotNull] VoxScriptParser.Table_member_dictContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.table_member_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTable_member_list([NotNull] VoxScriptParser.Table_member_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.table_member_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTable_member_list([NotNull] VoxScriptParser.Table_member_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.table_member"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTable_member([NotNull] VoxScriptParser.Table_memberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.table_member"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTable_member([NotNull] VoxScriptParser.Table_memberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.table_key"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTable_key([NotNull] VoxScriptParser.Table_keyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.table_key"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTable_key([NotNull] VoxScriptParser.Table_keyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.lambda"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLambda([NotNull] VoxScriptParser.LambdaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.lambda"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLambda([NotNull] VoxScriptParser.LambdaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifier([NotNull] VoxScriptParser.IdentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifier([NotNull] VoxScriptParser.IdentifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.postfix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPostfix([NotNull] VoxScriptParser.PostfixContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.postfix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPostfix([NotNull] VoxScriptParser.PostfixContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.id_postfix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterId_postfix([NotNull] VoxScriptParser.Id_postfixContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.id_postfix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitId_postfix([NotNull] VoxScriptParser.Id_postfixContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.expression_postfix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression_postfix([NotNull] VoxScriptParser.Expression_postfixContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.expression_postfix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression_postfix([NotNull] VoxScriptParser.Expression_postfixContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.function_postfix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction_postfix([NotNull] VoxScriptParser.Function_postfixContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.function_postfix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction_postfix([NotNull] VoxScriptParser.Function_postfixContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.function_params"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction_params([NotNull] VoxScriptParser.Function_paramsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.function_params"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction_params([NotNull] VoxScriptParser.Function_paramsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.var_inst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVar_inst([NotNull] VoxScriptParser.Var_instContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.var_inst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVar_inst([NotNull] VoxScriptParser.Var_instContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
