//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from VoxScript.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="VoxScriptParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IVoxScriptListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] VoxScriptParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] VoxScriptParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] VoxScriptParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] VoxScriptParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] VoxScriptParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] VoxScriptParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.print"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrint([NotNull] VoxScriptParser.PrintContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.print"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrint([NotNull] VoxScriptParser.PrintContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.var_define"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVar_define([NotNull] VoxScriptParser.Var_defineContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.var_define"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVar_define([NotNull] VoxScriptParser.Var_defineContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.val_assign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVal_assign([NotNull] VoxScriptParser.Val_assignContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.val_assign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVal_assign([NotNull] VoxScriptParser.Val_assignContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.arith_assign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArith_assign([NotNull] VoxScriptParser.Arith_assignContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.arith_assign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArith_assign([NotNull] VoxScriptParser.Arith_assignContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.val_increment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVal_increment([NotNull] VoxScriptParser.Val_incrementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.val_increment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVal_increment([NotNull] VoxScriptParser.Val_incrementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.func_define"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunc_define([NotNull] VoxScriptParser.Func_defineContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.func_define"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunc_define([NotNull] VoxScriptParser.Func_defineContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.func_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunc_call([NotNull] VoxScriptParser.Func_callContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.func_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunc_call([NotNull] VoxScriptParser.Func_callContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.cont_while"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCont_while([NotNull] VoxScriptParser.Cont_whileContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.cont_while"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCont_while([NotNull] VoxScriptParser.Cont_whileContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.cont_for"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCont_for([NotNull] VoxScriptParser.Cont_forContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.cont_for"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCont_for([NotNull] VoxScriptParser.Cont_forContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.cont_foreach"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCont_foreach([NotNull] VoxScriptParser.Cont_foreachContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.cont_foreach"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCont_foreach([NotNull] VoxScriptParser.Cont_foreachContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.cont_return"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCont_return([NotNull] VoxScriptParser.Cont_returnContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.cont_return"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCont_return([NotNull] VoxScriptParser.Cont_returnContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.cont_continue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCont_continue([NotNull] VoxScriptParser.Cont_continueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.cont_continue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCont_continue([NotNull] VoxScriptParser.Cont_continueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.cont_break"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCont_break([NotNull] VoxScriptParser.Cont_breakContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.cont_break"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCont_break([NotNull] VoxScriptParser.Cont_breakContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.cont_if"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCont_if([NotNull] VoxScriptParser.Cont_ifContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.cont_if"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCont_if([NotNull] VoxScriptParser.Cont_ifContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.cont_else"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCont_else([NotNull] VoxScriptParser.Cont_elseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.cont_else"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCont_else([NotNull] VoxScriptParser.Cont_elseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.type_annotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType_annotation([NotNull] VoxScriptParser.Type_annotationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.type_annotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType_annotation([NotNull] VoxScriptParser.Type_annotationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] VoxScriptParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] VoxScriptParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.table_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTable_definition([NotNull] VoxScriptParser.Table_definitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.table_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTable_definition([NotNull] VoxScriptParser.Table_definitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.table_member_dict"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTable_member_dict([NotNull] VoxScriptParser.Table_member_dictContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.table_member_dict"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTable_member_dict([NotNull] VoxScriptParser.Table_member_dictContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.table_member_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTable_member_list([NotNull] VoxScriptParser.Table_member_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.table_member_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTable_member_list([NotNull] VoxScriptParser.Table_member_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.table_member"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTable_member([NotNull] VoxScriptParser.Table_memberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.table_member"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTable_member([NotNull] VoxScriptParser.Table_memberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.table_key"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTable_key([NotNull] VoxScriptParser.Table_keyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.table_key"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTable_key([NotNull] VoxScriptParser.Table_keyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.lambda"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLambda([NotNull] VoxScriptParser.LambdaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.lambda"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLambda([NotNull] VoxScriptParser.LambdaContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifier([NotNull] VoxScriptParser.IdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifier([NotNull] VoxScriptParser.IdentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.postfix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPostfix([NotNull] VoxScriptParser.PostfixContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.postfix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPostfix([NotNull] VoxScriptParser.PostfixContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.id_postfix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterId_postfix([NotNull] VoxScriptParser.Id_postfixContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.id_postfix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitId_postfix([NotNull] VoxScriptParser.Id_postfixContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.expression_postfix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression_postfix([NotNull] VoxScriptParser.Expression_postfixContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.expression_postfix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression_postfix([NotNull] VoxScriptParser.Expression_postfixContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.function_postfix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_postfix([NotNull] VoxScriptParser.Function_postfixContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.function_postfix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_postfix([NotNull] VoxScriptParser.Function_postfixContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.function_params"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_params([NotNull] VoxScriptParser.Function_paramsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.function_params"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_params([NotNull] VoxScriptParser.Function_paramsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.var_inst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVar_inst([NotNull] VoxScriptParser.Var_instContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.var_inst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVar_inst([NotNull] VoxScriptParser.Var_instContext context);
}
