//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from VoxScript.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public partial class VoxScriptParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, VAR=9, 
		FUNC=10, FOR=11, FOREACH=12, WHILE=13, IN=14, CONTINUE=15, BREAK=16, IF=17, 
		ELSE=18, NUMBER=19, STRING=20, BOOLEAN=21, NULL=22, TUPLE=23, TRUE=24, 
		FALSE=25, ID=26, SEMICOLON=27, COLON=28, EXCLAMATION=29, QUOTATION=30, 
		LEFT_PAREN=31, RIGHT_PAREN=32, LEFT_BRACE=33, RIGHT_BRACE=34, LEFT_CURLY=35, 
		RIGHT_CURLY=36, UNARY=37, MUL_DIV=38, ADD_SUB=39, COMPARE=40, ASSIGNMENT=41, 
		WS=42, LINE_COMMENT=43, MULTILINE_COMMENT=44, INCREMENT=45, DECREMENT=46, 
		ADD_DIRECT=47, SUB_DIRECT=48, MULT_DIRECT=49, DIV_DIRECT=50, EXPO_DIRECT=51, 
		MOD_DIRECT=52, COND_EQUAL=53, COND_NOTEQUAL=54, COND_GREATERTHAN=55, COND_LESSTHAN=56, 
		COND_GREATEROREQUAL=57, COND_LESSOREQUAL=58, COND_AND=59, COND_OR=60;
	public const int
		RULE_program = 0, RULE_block = 1, RULE_statement = 2, RULE_print = 3, 
		RULE_var_define = 4, RULE_val_assign = 5, RULE_arith_assign = 6, RULE_val_increment = 7, 
		RULE_func_define = 8, RULE_func_call = 9, RULE_cont_while = 10, RULE_cont_for = 11, 
		RULE_cont_foreach = 12, RULE_cont_return = 13, RULE_cont_continue = 14, 
		RULE_cont_break = 15, RULE_cont_if = 16, RULE_cont_else = 17, RULE_type_annotation = 18, 
		RULE_expression = 19, RULE_table_definition = 20, RULE_table_member_dict = 21, 
		RULE_table_member_list = 22, RULE_table_member = 23, RULE_table_key = 24, 
		RULE_lambda = 25, RULE_identifier = 26, RULE_postfix = 27, RULE_id_postfix = 28, 
		RULE_expression_postfix = 29, RULE_function_postfix = 30, RULE_function_params = 31, 
		RULE_var_inst = 32;
	public static readonly string[] ruleNames = {
		"program", "block", "statement", "print", "var_define", "val_assign", 
		"arith_assign", "val_increment", "func_define", "func_call", "cont_while", 
		"cont_for", "cont_foreach", "cont_return", "cont_continue", "cont_break", 
		"cont_if", "cont_else", "type_annotation", "expression", "table_definition", 
		"table_member_dict", "table_member_list", "table_member", "table_key", 
		"lambda", "identifier", "postfix", "id_postfix", "expression_postfix", 
		"function_postfix", "function_params", "var_inst"
	};

	private static readonly string[] _LiteralNames = {
		null, "'print'", "'='", "','", "'return'", "'^'", "'?'", "'->'", "'.'", 
		"'var'", "'func'", "'for'", "'foreach'", "'while'", "'in'", "'continue'", 
		"'break'", "'if'", "'else'", null, null, null, "'null'", "'...'", "'true'", 
		"'false'", null, "';'", "':'", "'!'", "'\"'", "'('", "')'", "'['", "']'", 
		"'{'", "'}'", null, null, null, null, null, null, null, null, "'++'", 
		"'--'", "'+='", "'-='", "'*='", "'/='", "'^='", "'%='", "'=='", "'!='", 
		"'>'", "'<'", "'>='", "'<='", "'&&'", "'||'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, "VAR", "FUNC", "FOR", 
		"FOREACH", "WHILE", "IN", "CONTINUE", "BREAK", "IF", "ELSE", "NUMBER", 
		"STRING", "BOOLEAN", "NULL", "TUPLE", "TRUE", "FALSE", "ID", "SEMICOLON", 
		"COLON", "EXCLAMATION", "QUOTATION", "LEFT_PAREN", "RIGHT_PAREN", "LEFT_BRACE", 
		"RIGHT_BRACE", "LEFT_CURLY", "RIGHT_CURLY", "UNARY", "MUL_DIV", "ADD_SUB", 
		"COMPARE", "ASSIGNMENT", "WS", "LINE_COMMENT", "MULTILINE_COMMENT", "INCREMENT", 
		"DECREMENT", "ADD_DIRECT", "SUB_DIRECT", "MULT_DIRECT", "DIV_DIRECT", 
		"EXPO_DIRECT", "MOD_DIRECT", "COND_EQUAL", "COND_NOTEQUAL", "COND_GREATERTHAN", 
		"COND_LESSTHAN", "COND_GREATEROREQUAL", "COND_LESSOREQUAL", "COND_AND", 
		"COND_OR"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "VoxScript.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static VoxScriptParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public VoxScriptParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public VoxScriptParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ProgramContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public BlockContext block() {
			return GetRuleContext<BlockContext>(0);
		}
		public ProgramContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_program; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterProgram(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitProgram(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitProgram(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ProgramContext program() {
		ProgramContext _localctx = new ProgramContext(Context, State);
		EnterRule(_localctx, 0, RULE_program);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 66;
			block();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BlockContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] SEMICOLON() { return GetTokens(VoxScriptParser.SEMICOLON); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMICOLON(int i) {
			return GetToken(VoxScriptParser.SEMICOLON, i);
		}
		public BlockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_block; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterBlock(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitBlock(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBlock(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BlockContext block() {
		BlockContext _localctx = new BlockContext(Context, State);
		EnterRule(_localctx, 2, RULE_block);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 74;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 67354130L) != 0)) {
				{
				{
				State = 68;
				statement();
				State = 70;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==SEMICOLON) {
					{
					State = 69;
					Match(SEMICOLON);
					}
				}

				}
				}
				State = 76;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StatementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Var_defineContext var_define() {
			return GetRuleContext<Var_defineContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Val_assignContext val_assign() {
			return GetRuleContext<Val_assignContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Arith_assignContext arith_assign() {
			return GetRuleContext<Arith_assignContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Val_incrementContext val_increment() {
			return GetRuleContext<Val_incrementContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Func_callContext func_call() {
			return GetRuleContext<Func_callContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Func_defineContext func_define() {
			return GetRuleContext<Func_defineContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Cont_returnContext cont_return() {
			return GetRuleContext<Cont_returnContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Cont_continueContext cont_continue() {
			return GetRuleContext<Cont_continueContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Cont_breakContext cont_break() {
			return GetRuleContext<Cont_breakContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Cont_whileContext cont_while() {
			return GetRuleContext<Cont_whileContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Cont_forContext cont_for() {
			return GetRuleContext<Cont_forContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Cont_foreachContext cont_foreach() {
			return GetRuleContext<Cont_foreachContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Cont_ifContext cont_if() {
			return GetRuleContext<Cont_ifContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public PrintContext print() {
			return GetRuleContext<PrintContext>(0);
		}
		public StatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterStatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitStatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StatementContext statement() {
		StatementContext _localctx = new StatementContext(Context, State);
		EnterRule(_localctx, 4, RULE_statement);
		try {
			State = 91;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,2,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 77;
				var_define();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 78;
				val_assign();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 79;
				arith_assign();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 80;
				val_increment();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 81;
				func_call();
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 82;
				func_define();
				}
				break;
			case 7:
				EnterOuterAlt(_localctx, 7);
				{
				State = 83;
				cont_return();
				}
				break;
			case 8:
				EnterOuterAlt(_localctx, 8);
				{
				State = 84;
				cont_continue();
				}
				break;
			case 9:
				EnterOuterAlt(_localctx, 9);
				{
				State = 85;
				cont_break();
				}
				break;
			case 10:
				EnterOuterAlt(_localctx, 10);
				{
				State = 86;
				cont_while();
				}
				break;
			case 11:
				EnterOuterAlt(_localctx, 11);
				{
				State = 87;
				cont_for();
				}
				break;
			case 12:
				EnterOuterAlt(_localctx, 12);
				{
				State = 88;
				cont_foreach();
				}
				break;
			case 13:
				EnterOuterAlt(_localctx, 13);
				{
				State = 89;
				cont_if();
				}
				break;
			case 14:
				EnterOuterAlt(_localctx, 14);
				{
				State = 90;
				print();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PrintContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public PrintContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_print; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterPrint(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitPrint(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPrint(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PrintContext print() {
		PrintContext _localctx = new PrintContext(Context, State);
		EnterRule(_localctx, 6, RULE_print);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 93;
			Match(T__0);
			State = 94;
			expression(0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Var_defineContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode VAR() { return GetToken(VoxScriptParser.VAR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Var_instContext var_inst() {
			return GetRuleContext<Var_instContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public Var_defineContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_var_define; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterVar_define(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitVar_define(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVar_define(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Var_defineContext var_define() {
		Var_defineContext _localctx = new Var_defineContext(Context, State);
		EnterRule(_localctx, 8, RULE_var_define);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 96;
			Match(VAR);
			State = 97;
			var_inst();
			State = 98;
			Match(T__1);
			State = 99;
			expression(0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Val_assignContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public IdentifierContext identifier() {
			return GetRuleContext<IdentifierContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public Val_assignContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_val_assign; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterVal_assign(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitVal_assign(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVal_assign(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Val_assignContext val_assign() {
		Val_assignContext _localctx = new Val_assignContext(Context, State);
		EnterRule(_localctx, 10, RULE_val_assign);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 101;
			identifier();
			State = 102;
			Match(T__1);
			State = 103;
			expression(0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Arith_assignContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public IdentifierContext identifier() {
			return GetRuleContext<IdentifierContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ASSIGNMENT() { return GetToken(VoxScriptParser.ASSIGNMENT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public Arith_assignContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arith_assign; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterArith_assign(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitArith_assign(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArith_assign(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Arith_assignContext arith_assign() {
		Arith_assignContext _localctx = new Arith_assignContext(Context, State);
		EnterRule(_localctx, 12, RULE_arith_assign);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 105;
			identifier();
			State = 106;
			Match(ASSIGNMENT);
			State = 107;
			expression(0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Val_incrementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public IdentifierContext identifier() {
			return GetRuleContext<IdentifierContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INCREMENT() { return GetToken(VoxScriptParser.INCREMENT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DECREMENT() { return GetToken(VoxScriptParser.DECREMENT, 0); }
		public Val_incrementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_val_increment; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterVal_increment(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitVal_increment(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVal_increment(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Val_incrementContext val_increment() {
		Val_incrementContext _localctx = new Val_incrementContext(Context, State);
		EnterRule(_localctx, 14, RULE_val_increment);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 109;
			identifier();
			State = 110;
			_la = TokenStream.LA(1);
			if ( !(_la==INCREMENT || _la==DECREMENT) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Func_defineContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FUNC() { return GetToken(VoxScriptParser.FUNC, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(VoxScriptParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Function_paramsContext function_params() {
			return GetRuleContext<Function_paramsContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LEFT_CURLY() { return GetToken(VoxScriptParser.LEFT_CURLY, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public BlockContext block() {
			return GetRuleContext<BlockContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RIGHT_CURLY() { return GetToken(VoxScriptParser.RIGHT_CURLY, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Type_annotationContext type_annotation() {
			return GetRuleContext<Type_annotationContext>(0);
		}
		public Func_defineContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_func_define; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterFunc_define(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitFunc_define(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunc_define(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Func_defineContext func_define() {
		Func_defineContext _localctx = new Func_defineContext(Context, State);
		EnterRule(_localctx, 16, RULE_func_define);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 112;
			Match(FUNC);
			State = 113;
			Match(ID);
			State = 114;
			function_params();
			State = 116;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==COLON) {
				{
				State = 115;
				type_annotation();
				}
			}

			State = 118;
			Match(LEFT_CURLY);
			State = 119;
			block();
			State = 120;
			Match(RIGHT_CURLY);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Func_callContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public IdentifierContext identifier() {
			return GetRuleContext<IdentifierContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Function_postfixContext function_postfix() {
			return GetRuleContext<Function_postfixContext>(0);
		}
		public Func_callContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_func_call; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterFunc_call(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitFunc_call(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunc_call(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Func_callContext func_call() {
		Func_callContext _localctx = new Func_callContext(Context, State);
		EnterRule(_localctx, 18, RULE_func_call);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 122;
			identifier();
			State = 123;
			function_postfix();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Cont_whileContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WHILE() { return GetToken(VoxScriptParser.WHILE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LEFT_PAREN() { return GetToken(VoxScriptParser.LEFT_PAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RIGHT_PAREN() { return GetToken(VoxScriptParser.RIGHT_PAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LEFT_CURLY() { return GetToken(VoxScriptParser.LEFT_CURLY, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public BlockContext block() {
			return GetRuleContext<BlockContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RIGHT_CURLY() { return GetToken(VoxScriptParser.RIGHT_CURLY, 0); }
		public Cont_whileContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_cont_while; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterCont_while(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitCont_while(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCont_while(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Cont_whileContext cont_while() {
		Cont_whileContext _localctx = new Cont_whileContext(Context, State);
		EnterRule(_localctx, 20, RULE_cont_while);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 125;
			Match(WHILE);
			State = 126;
			Match(LEFT_PAREN);
			State = 127;
			expression(0);
			State = 128;
			Match(RIGHT_PAREN);
			State = 129;
			Match(LEFT_CURLY);
			State = 130;
			block();
			State = 131;
			Match(RIGHT_CURLY);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Cont_forContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FOR() { return GetToken(VoxScriptParser.FOR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LEFT_PAREN() { return GetToken(VoxScriptParser.LEFT_PAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(VoxScriptParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RIGHT_PAREN() { return GetToken(VoxScriptParser.RIGHT_PAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LEFT_CURLY() { return GetToken(VoxScriptParser.LEFT_CURLY, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public BlockContext block() {
			return GetRuleContext<BlockContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RIGHT_CURLY() { return GetToken(VoxScriptParser.RIGHT_CURLY, 0); }
		public Cont_forContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_cont_for; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterCont_for(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitCont_for(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCont_for(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Cont_forContext cont_for() {
		Cont_forContext _localctx = new Cont_forContext(Context, State);
		EnterRule(_localctx, 22, RULE_cont_for);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 133;
			Match(FOR);
			State = 134;
			Match(LEFT_PAREN);
			State = 135;
			Match(ID);
			State = 138;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__1) {
				{
				State = 136;
				Match(T__1);
				State = 137;
				expression(0);
				}
			}

			State = 140;
			Match(T__2);
			State = 141;
			expression(0);
			State = 144;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__2) {
				{
				State = 142;
				Match(T__2);
				State = 143;
				expression(0);
				}
			}

			State = 146;
			Match(RIGHT_PAREN);
			State = 147;
			Match(LEFT_CURLY);
			State = 148;
			block();
			State = 149;
			Match(RIGHT_CURLY);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Cont_foreachContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FOREACH() { return GetToken(VoxScriptParser.FOREACH, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LEFT_PAREN() { return GetToken(VoxScriptParser.LEFT_PAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Var_instContext[] var_inst() {
			return GetRuleContexts<Var_instContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Var_instContext var_inst(int i) {
			return GetRuleContext<Var_instContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IN() { return GetToken(VoxScriptParser.IN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RIGHT_PAREN() { return GetToken(VoxScriptParser.RIGHT_PAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LEFT_CURLY() { return GetToken(VoxScriptParser.LEFT_CURLY, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public BlockContext block() {
			return GetRuleContext<BlockContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RIGHT_CURLY() { return GetToken(VoxScriptParser.RIGHT_CURLY, 0); }
		public Cont_foreachContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_cont_foreach; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterCont_foreach(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitCont_foreach(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCont_foreach(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Cont_foreachContext cont_foreach() {
		Cont_foreachContext _localctx = new Cont_foreachContext(Context, State);
		EnterRule(_localctx, 24, RULE_cont_foreach);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 151;
			Match(FOREACH);
			State = 152;
			Match(LEFT_PAREN);
			State = 153;
			var_inst();
			State = 154;
			Match(T__2);
			State = 155;
			var_inst();
			State = 156;
			Match(IN);
			State = 157;
			expression(0);
			State = 158;
			Match(RIGHT_PAREN);
			State = 159;
			Match(LEFT_CURLY);
			State = 160;
			block();
			State = 161;
			Match(RIGHT_CURLY);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Cont_returnContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public Cont_returnContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_cont_return; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterCont_return(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitCont_return(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCont_return(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Cont_returnContext cont_return() {
		Cont_returnContext _localctx = new Cont_returnContext(Context, State);
		EnterRule(_localctx, 26, RULE_cont_return);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 163;
			Match(T__3);
			State = 165;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,6,Context) ) {
			case 1:
				{
				State = 164;
				expression(0);
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Cont_continueContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CONTINUE() { return GetToken(VoxScriptParser.CONTINUE, 0); }
		public Cont_continueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_cont_continue; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterCont_continue(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitCont_continue(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCont_continue(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Cont_continueContext cont_continue() {
		Cont_continueContext _localctx = new Cont_continueContext(Context, State);
		EnterRule(_localctx, 28, RULE_cont_continue);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 167;
			Match(CONTINUE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Cont_breakContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BREAK() { return GetToken(VoxScriptParser.BREAK, 0); }
		public Cont_breakContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_cont_break; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterCont_break(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitCont_break(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCont_break(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Cont_breakContext cont_break() {
		Cont_breakContext _localctx = new Cont_breakContext(Context, State);
		EnterRule(_localctx, 30, RULE_cont_break);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 169;
			Match(BREAK);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Cont_ifContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IF() { return GetToken(VoxScriptParser.IF, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LEFT_PAREN() { return GetToken(VoxScriptParser.LEFT_PAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RIGHT_PAREN() { return GetToken(VoxScriptParser.RIGHT_PAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement() {
			return GetRuleContext<StatementContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LEFT_CURLY() { return GetToken(VoxScriptParser.LEFT_CURLY, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public BlockContext block() {
			return GetRuleContext<BlockContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RIGHT_CURLY() { return GetToken(VoxScriptParser.RIGHT_CURLY, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Cont_elseContext cont_else() {
			return GetRuleContext<Cont_elseContext>(0);
		}
		public Cont_ifContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_cont_if; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterCont_if(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitCont_if(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCont_if(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Cont_ifContext cont_if() {
		Cont_ifContext _localctx = new Cont_ifContext(Context, State);
		EnterRule(_localctx, 32, RULE_cont_if);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 171;
			Match(IF);
			State = 172;
			Match(LEFT_PAREN);
			State = 173;
			expression(0);
			State = 174;
			Match(RIGHT_PAREN);
			State = 180;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__0:
			case T__3:
			case VAR:
			case FUNC:
			case FOR:
			case FOREACH:
			case WHILE:
			case CONTINUE:
			case BREAK:
			case IF:
			case ID:
				{
				State = 175;
				statement();
				}
				break;
			case LEFT_CURLY:
				{
				State = 176;
				Match(LEFT_CURLY);
				State = 177;
				block();
				State = 178;
				Match(RIGHT_CURLY);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			State = 183;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,8,Context) ) {
			case 1:
				{
				State = 182;
				cont_else();
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Cont_elseContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ELSE() { return GetToken(VoxScriptParser.ELSE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement() {
			return GetRuleContext<StatementContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LEFT_CURLY() { return GetToken(VoxScriptParser.LEFT_CURLY, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public BlockContext block() {
			return GetRuleContext<BlockContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RIGHT_CURLY() { return GetToken(VoxScriptParser.RIGHT_CURLY, 0); }
		public Cont_elseContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_cont_else; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterCont_else(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitCont_else(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCont_else(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Cont_elseContext cont_else() {
		Cont_elseContext _localctx = new Cont_elseContext(Context, State);
		EnterRule(_localctx, 34, RULE_cont_else);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 185;
			Match(ELSE);
			State = 191;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__0:
			case T__3:
			case VAR:
			case FUNC:
			case FOR:
			case FOREACH:
			case WHILE:
			case CONTINUE:
			case BREAK:
			case IF:
			case ID:
				{
				State = 186;
				statement();
				}
				break;
			case LEFT_CURLY:
				{
				State = 187;
				Match(LEFT_CURLY);
				State = 188;
				block();
				State = 189;
				Match(RIGHT_CURLY);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Type_annotationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COLON() { return GetToken(VoxScriptParser.COLON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(VoxScriptParser.ID, 0); }
		public Type_annotationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_type_annotation; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterType_annotation(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitType_annotation(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitType_annotation(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Type_annotationContext type_annotation() {
		Type_annotationContext _localctx = new Type_annotationContext(Context, State);
		EnterRule(_localctx, 36, RULE_type_annotation);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 193;
			Match(COLON);
			State = 194;
			Match(ID);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpressionContext : ParserRuleContext {
		public ExpressionContext left;
		public ExpressionContext condition;
		public ExpressionContext paren;
		public IToken unary;
		public ExpressionContext expr;
		public IToken op;
		public ExpressionContext right;
		public ExpressionContext primary;
		public ExpressionContext secondary;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LEFT_PAREN() { return GetToken(VoxScriptParser.LEFT_PAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RIGHT_PAREN() { return GetToken(VoxScriptParser.RIGHT_PAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode UNARY() { return GetToken(VoxScriptParser.UNARY, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER() { return GetToken(VoxScriptParser.NUMBER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(VoxScriptParser.STRING, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BOOLEAN() { return GetToken(VoxScriptParser.BOOLEAN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NULL() { return GetToken(VoxScriptParser.NULL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Table_definitionContext table_definition() {
			return GetRuleContext<Table_definitionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Func_callContext func_call() {
			return GetRuleContext<Func_callContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public IdentifierContext identifier() {
			return GetRuleContext<IdentifierContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public LambdaContext lambda() {
			return GetRuleContext<LambdaContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MUL_DIV() { return GetToken(VoxScriptParser.MUL_DIV, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ADD_SUB() { return GetToken(VoxScriptParser.ADD_SUB, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COND_AND() { return GetToken(VoxScriptParser.COND_AND, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COND_OR() { return GetToken(VoxScriptParser.COND_OR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMPARE() { return GetToken(VoxScriptParser.COMPARE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COLON() { return GetToken(VoxScriptParser.COLON, 0); }
		public ExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterExpression(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitExpression(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExpressionContext expression() {
		return expression(0);
	}

	private ExpressionContext expression(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ExpressionContext _localctx = new ExpressionContext(Context, _parentState);
		ExpressionContext _prevctx = _localctx;
		int _startState = 38;
		EnterRecursionRule(_localctx, 38, RULE_expression, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 211;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,10,Context) ) {
			case 1:
				{
				State = 197;
				Match(LEFT_PAREN);
				State = 198;
				_localctx.paren = expression(0);
				State = 199;
				Match(RIGHT_PAREN);
				}
				break;
			case 2:
				{
				State = 201;
				_localctx.unary = Match(UNARY);
				State = 202;
				_localctx.expr = expression(16);
				}
				break;
			case 3:
				{
				State = 203;
				Match(NUMBER);
				}
				break;
			case 4:
				{
				State = 204;
				Match(STRING);
				}
				break;
			case 5:
				{
				State = 205;
				Match(BOOLEAN);
				}
				break;
			case 6:
				{
				State = 206;
				Match(NULL);
				}
				break;
			case 7:
				{
				State = 207;
				table_definition();
				}
				break;
			case 8:
				{
				State = 208;
				func_call();
				}
				break;
			case 9:
				{
				State = 209;
				identifier();
				}
				break;
			case 10:
				{
				State = 210;
				lambda();
				}
				break;
			}
			Context.Stop = TokenStream.LT(-1);
			State = 239;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,12,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 237;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,11,Context) ) {
					case 1:
						{
						_localctx = new ExpressionContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 213;
						if (!(Precpred(Context, 15))) throw new FailedPredicateException(this, "Precpred(Context, 15)");
						State = 214;
						_localctx.op = Match(T__4);
						State = 215;
						_localctx.right = expression(16);
						}
						break;
					case 2:
						{
						_localctx = new ExpressionContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 216;
						if (!(Precpred(Context, 14))) throw new FailedPredicateException(this, "Precpred(Context, 14)");
						State = 217;
						_localctx.op = Match(MUL_DIV);
						State = 218;
						_localctx.right = expression(15);
						}
						break;
					case 3:
						{
						_localctx = new ExpressionContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 219;
						if (!(Precpred(Context, 13))) throw new FailedPredicateException(this, "Precpred(Context, 13)");
						State = 220;
						_localctx.op = Match(ADD_SUB);
						State = 221;
						_localctx.right = expression(14);
						}
						break;
					case 4:
						{
						_localctx = new ExpressionContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 222;
						if (!(Precpred(Context, 12))) throw new FailedPredicateException(this, "Precpred(Context, 12)");
						State = 223;
						_localctx.op = Match(COND_AND);
						State = 224;
						_localctx.right = expression(13);
						}
						break;
					case 5:
						{
						_localctx = new ExpressionContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 225;
						if (!(Precpred(Context, 11))) throw new FailedPredicateException(this, "Precpred(Context, 11)");
						State = 226;
						_localctx.op = Match(COND_OR);
						State = 227;
						_localctx.right = expression(12);
						}
						break;
					case 6:
						{
						_localctx = new ExpressionContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 228;
						if (!(Precpred(Context, 10))) throw new FailedPredicateException(this, "Precpred(Context, 10)");
						State = 229;
						_localctx.op = Match(COMPARE);
						State = 230;
						_localctx.right = expression(11);
						}
						break;
					case 7:
						{
						_localctx = new ExpressionContext(_parentctx, _parentState);
						_localctx.condition = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 231;
						if (!(Precpred(Context, 9))) throw new FailedPredicateException(this, "Precpred(Context, 9)");
						State = 232;
						Match(T__5);
						State = 233;
						_localctx.primary = expression(0);
						State = 234;
						Match(COLON);
						State = 235;
						_localctx.secondary = expression(10);
						}
						break;
					}
					} 
				}
				State = 241;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,12,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class Table_definitionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LEFT_CURLY() { return GetToken(VoxScriptParser.LEFT_CURLY, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RIGHT_CURLY() { return GetToken(VoxScriptParser.RIGHT_CURLY, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Table_member_dictContext table_member_dict() {
			return GetRuleContext<Table_member_dictContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Table_member_listContext table_member_list() {
			return GetRuleContext<Table_member_listContext>(0);
		}
		public Table_definitionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_table_definition; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterTable_definition(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitTable_definition(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTable_definition(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Table_definitionContext table_definition() {
		Table_definitionContext _localctx = new Table_definitionContext(Context, State);
		EnterRule(_localctx, 40, RULE_table_definition);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 242;
			Match(LEFT_CURLY);
			State = 245;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,13,Context) ) {
			case 1:
				{
				State = 243;
				table_member_dict();
				}
				break;
			case 2:
				{
				State = 244;
				table_member_list();
				}
				break;
			}
			State = 247;
			Match(RIGHT_CURLY);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Table_member_dictContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Table_memberContext[] table_member() {
			return GetRuleContexts<Table_memberContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Table_memberContext table_member(int i) {
			return GetRuleContext<Table_memberContext>(i);
		}
		public Table_member_dictContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_table_member_dict; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterTable_member_dict(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitTable_member_dict(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTable_member_dict(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Table_member_dictContext table_member_dict() {
		Table_member_dictContext _localctx = new Table_member_dictContext(Context, State);
		EnterRule(_localctx, 42, RULE_table_member_dict);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 249;
			table_member();
			State = 254;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,14,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 250;
					Match(T__2);
					State = 251;
					table_member();
					}
					} 
				}
				State = 256;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,14,Context);
			}
			State = 258;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__2) {
				{
				State = 257;
				Match(T__2);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Table_member_listContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public Table_member_listContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_table_member_list; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterTable_member_list(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitTable_member_list(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTable_member_list(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Table_member_listContext table_member_list() {
		Table_member_listContext _localctx = new Table_member_listContext(Context, State);
		EnterRule(_localctx, 44, RULE_table_member_list);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 260;
			expression(0);
			State = 265;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,16,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 261;
					Match(T__2);
					State = 262;
					expression(0);
					}
					} 
				}
				State = 267;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,16,Context);
			}
			State = 269;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__2) {
				{
				State = 268;
				Match(T__2);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Table_memberContext : ParserRuleContext {
		public Table_keyContext key;
		public ExpressionContext value;
		[System.Diagnostics.DebuggerNonUserCode] public Table_keyContext table_key() {
			return GetRuleContext<Table_keyContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public Table_memberContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_table_member; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterTable_member(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitTable_member(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTable_member(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Table_memberContext table_member() {
		Table_memberContext _localctx = new Table_memberContext(Context, State);
		EnterRule(_localctx, 46, RULE_table_member);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 271;
			_localctx.key = table_key();
			State = 272;
			Match(T__1);
			State = 273;
			_localctx.value = expression(0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Table_keyContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(VoxScriptParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public Table_keyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_table_key; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterTable_key(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitTable_key(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTable_key(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Table_keyContext table_key() {
		Table_keyContext _localctx = new Table_keyContext(Context, State);
		EnterRule(_localctx, 48, RULE_table_key);
		try {
			State = 277;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,18,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 275;
				Match(ID);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 276;
				expression(0);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LambdaContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Function_paramsContext function_params() {
			return GetRuleContext<Function_paramsContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LEFT_CURLY() { return GetToken(VoxScriptParser.LEFT_CURLY, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public BlockContext block() {
			return GetRuleContext<BlockContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RIGHT_CURLY() { return GetToken(VoxScriptParser.RIGHT_CURLY, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement() {
			return GetRuleContext<StatementContext>(0);
		}
		public LambdaContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_lambda; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterLambda(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitLambda(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLambda(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LambdaContext lambda() {
		LambdaContext _localctx = new LambdaContext(Context, State);
		EnterRule(_localctx, 50, RULE_lambda);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 279;
			function_params();
			State = 280;
			Match(T__6);
			State = 286;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case LEFT_CURLY:
				{
				State = 281;
				Match(LEFT_CURLY);
				State = 282;
				block();
				State = 283;
				Match(RIGHT_CURLY);
				}
				break;
			case T__0:
			case T__3:
			case VAR:
			case FUNC:
			case FOR:
			case FOREACH:
			case WHILE:
			case CONTINUE:
			case BREAK:
			case IF:
			case ID:
				{
				State = 285;
				statement();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IdentifierContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(VoxScriptParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public PostfixContext[] postfix() {
			return GetRuleContexts<PostfixContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public PostfixContext postfix(int i) {
			return GetRuleContext<PostfixContext>(i);
		}
		public IdentifierContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_identifier; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterIdentifier(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitIdentifier(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIdentifier(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public IdentifierContext identifier() {
		IdentifierContext _localctx = new IdentifierContext(Context, State);
		EnterRule(_localctx, 52, RULE_identifier);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 288;
			Match(ID);
			State = 292;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,20,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 289;
					postfix();
					}
					} 
				}
				State = 294;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,20,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PostfixContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Id_postfixContext id_postfix() {
			return GetRuleContext<Id_postfixContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Expression_postfixContext expression_postfix() {
			return GetRuleContext<Expression_postfixContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Function_postfixContext function_postfix() {
			return GetRuleContext<Function_postfixContext>(0);
		}
		public PostfixContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_postfix; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterPostfix(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitPostfix(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPostfix(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PostfixContext postfix() {
		PostfixContext _localctx = new PostfixContext(Context, State);
		EnterRule(_localctx, 54, RULE_postfix);
		try {
			State = 298;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__7:
				EnterOuterAlt(_localctx, 1);
				{
				State = 295;
				id_postfix();
				}
				break;
			case LEFT_BRACE:
				EnterOuterAlt(_localctx, 2);
				{
				State = 296;
				expression_postfix();
				}
				break;
			case LEFT_PAREN:
				EnterOuterAlt(_localctx, 3);
				{
				State = 297;
				function_postfix();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Id_postfixContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(VoxScriptParser.ID, 0); }
		public Id_postfixContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_id_postfix; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterId_postfix(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitId_postfix(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitId_postfix(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Id_postfixContext id_postfix() {
		Id_postfixContext _localctx = new Id_postfixContext(Context, State);
		EnterRule(_localctx, 56, RULE_id_postfix);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 300;
			Match(T__7);
			State = 301;
			Match(ID);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Expression_postfixContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LEFT_BRACE() { return GetToken(VoxScriptParser.LEFT_BRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RIGHT_BRACE() { return GetToken(VoxScriptParser.RIGHT_BRACE, 0); }
		public Expression_postfixContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression_postfix; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterExpression_postfix(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitExpression_postfix(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpression_postfix(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Expression_postfixContext expression_postfix() {
		Expression_postfixContext _localctx = new Expression_postfixContext(Context, State);
		EnterRule(_localctx, 58, RULE_expression_postfix);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 303;
			Match(LEFT_BRACE);
			State = 304;
			expression(0);
			State = 305;
			Match(RIGHT_BRACE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Function_postfixContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LEFT_PAREN() { return GetToken(VoxScriptParser.LEFT_PAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RIGHT_PAREN() { return GetToken(VoxScriptParser.RIGHT_PAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public Function_postfixContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_function_postfix; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterFunction_postfix(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitFunction_postfix(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunction_postfix(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Function_postfixContext function_postfix() {
		Function_postfixContext _localctx = new Function_postfixContext(Context, State);
		EnterRule(_localctx, 60, RULE_function_postfix);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 307;
			Match(LEFT_PAREN);
			State = 316;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 174021148672L) != 0)) {
				{
				State = 308;
				expression(0);
				State = 313;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__2) {
					{
					{
					State = 309;
					Match(T__2);
					State = 310;
					expression(0);
					}
					}
					State = 315;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
			}

			State = 318;
			Match(RIGHT_PAREN);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Function_paramsContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LEFT_PAREN() { return GetToken(VoxScriptParser.LEFT_PAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RIGHT_PAREN() { return GetToken(VoxScriptParser.RIGHT_PAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Var_instContext[] var_inst() {
			return GetRuleContexts<Var_instContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Var_instContext var_inst(int i) {
			return GetRuleContext<Var_instContext>(i);
		}
		public Function_paramsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_function_params; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterFunction_params(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitFunction_params(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunction_params(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Function_paramsContext function_params() {
		Function_paramsContext _localctx = new Function_paramsContext(Context, State);
		EnterRule(_localctx, 62, RULE_function_params);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 320;
			Match(LEFT_PAREN);
			State = 329;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==TUPLE || _la==ID) {
				{
				State = 321;
				var_inst();
				State = 326;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__2) {
					{
					{
					State = 322;
					Match(T__2);
					State = 323;
					var_inst();
					}
					}
					State = 328;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
			}

			State = 331;
			Match(RIGHT_PAREN);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Var_instContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(VoxScriptParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TUPLE() { return GetToken(VoxScriptParser.TUPLE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Type_annotationContext type_annotation() {
			return GetRuleContext<Type_annotationContext>(0);
		}
		public Var_instContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_var_inst; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterVar_inst(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitVar_inst(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVar_inst(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Var_instContext var_inst() {
		Var_instContext _localctx = new Var_instContext(Context, State);
		EnterRule(_localctx, 64, RULE_var_inst);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 333;
			_la = TokenStream.LA(1);
			if ( !(_la==TUPLE || _la==ID) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			State = 335;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==COLON) {
				{
				State = 334;
				type_annotation();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 19: return expression_sempred((ExpressionContext)_localctx, predIndex);
		}
		return true;
	}
	private bool expression_sempred(ExpressionContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 15);
		case 1: return Precpred(Context, 14);
		case 2: return Precpred(Context, 13);
		case 3: return Precpred(Context, 12);
		case 4: return Precpred(Context, 11);
		case 5: return Precpred(Context, 10);
		case 6: return Precpred(Context, 9);
		}
		return true;
	}

	private static int[] _serializedATN = {
		4,1,60,338,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,14,
		2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,2,20,7,20,2,21,7,21,
		2,22,7,22,2,23,7,23,2,24,7,24,2,25,7,25,2,26,7,26,2,27,7,27,2,28,7,28,
		2,29,7,29,2,30,7,30,2,31,7,31,2,32,7,32,1,0,1,0,1,1,1,1,3,1,71,8,1,5,1,
		73,8,1,10,1,12,1,76,9,1,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,
		2,1,2,1,2,3,2,92,8,2,1,3,1,3,1,3,1,4,1,4,1,4,1,4,1,4,1,5,1,5,1,5,1,5,1,
		6,1,6,1,6,1,6,1,7,1,7,1,7,1,8,1,8,1,8,1,8,3,8,117,8,8,1,8,1,8,1,8,1,8,
		1,9,1,9,1,9,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,11,1,11,1,11,1,11,
		1,11,3,11,139,8,11,1,11,1,11,1,11,1,11,3,11,145,8,11,1,11,1,11,1,11,1,
		11,1,11,1,12,1,12,1,12,1,12,1,12,1,12,1,12,1,12,1,12,1,12,1,12,1,12,1,
		13,1,13,3,13,166,8,13,1,14,1,14,1,15,1,15,1,16,1,16,1,16,1,16,1,16,1,16,
		1,16,1,16,1,16,3,16,181,8,16,1,16,3,16,184,8,16,1,17,1,17,1,17,1,17,1,
		17,1,17,3,17,192,8,17,1,18,1,18,1,18,1,19,1,19,1,19,1,19,1,19,1,19,1,19,
		1,19,1,19,1,19,1,19,1,19,1,19,1,19,1,19,3,19,212,8,19,1,19,1,19,1,19,1,
		19,1,19,1,19,1,19,1,19,1,19,1,19,1,19,1,19,1,19,1,19,1,19,1,19,1,19,1,
		19,1,19,1,19,1,19,1,19,1,19,1,19,5,19,238,8,19,10,19,12,19,241,9,19,1,
		20,1,20,1,20,3,20,246,8,20,1,20,1,20,1,21,1,21,1,21,5,21,253,8,21,10,21,
		12,21,256,9,21,1,21,3,21,259,8,21,1,22,1,22,1,22,5,22,264,8,22,10,22,12,
		22,267,9,22,1,22,3,22,270,8,22,1,23,1,23,1,23,1,23,1,24,1,24,3,24,278,
		8,24,1,25,1,25,1,25,1,25,1,25,1,25,1,25,3,25,287,8,25,1,26,1,26,5,26,291,
		8,26,10,26,12,26,294,9,26,1,27,1,27,1,27,3,27,299,8,27,1,28,1,28,1,28,
		1,29,1,29,1,29,1,29,1,30,1,30,1,30,1,30,5,30,312,8,30,10,30,12,30,315,
		9,30,3,30,317,8,30,1,30,1,30,1,31,1,31,1,31,1,31,5,31,325,8,31,10,31,12,
		31,328,9,31,3,31,330,8,31,1,31,1,31,1,32,1,32,3,32,336,8,32,1,32,0,1,38,
		33,0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,
		48,50,52,54,56,58,60,62,64,0,2,1,0,45,46,2,0,23,23,26,26,358,0,66,1,0,
		0,0,2,74,1,0,0,0,4,91,1,0,0,0,6,93,1,0,0,0,8,96,1,0,0,0,10,101,1,0,0,0,
		12,105,1,0,0,0,14,109,1,0,0,0,16,112,1,0,0,0,18,122,1,0,0,0,20,125,1,0,
		0,0,22,133,1,0,0,0,24,151,1,0,0,0,26,163,1,0,0,0,28,167,1,0,0,0,30,169,
		1,0,0,0,32,171,1,0,0,0,34,185,1,0,0,0,36,193,1,0,0,0,38,211,1,0,0,0,40,
		242,1,0,0,0,42,249,1,0,0,0,44,260,1,0,0,0,46,271,1,0,0,0,48,277,1,0,0,
		0,50,279,1,0,0,0,52,288,1,0,0,0,54,298,1,0,0,0,56,300,1,0,0,0,58,303,1,
		0,0,0,60,307,1,0,0,0,62,320,1,0,0,0,64,333,1,0,0,0,66,67,3,2,1,0,67,1,
		1,0,0,0,68,70,3,4,2,0,69,71,5,27,0,0,70,69,1,0,0,0,70,71,1,0,0,0,71,73,
		1,0,0,0,72,68,1,0,0,0,73,76,1,0,0,0,74,72,1,0,0,0,74,75,1,0,0,0,75,3,1,
		0,0,0,76,74,1,0,0,0,77,92,3,8,4,0,78,92,3,10,5,0,79,92,3,12,6,0,80,92,
		3,14,7,0,81,92,3,18,9,0,82,92,3,16,8,0,83,92,3,26,13,0,84,92,3,28,14,0,
		85,92,3,30,15,0,86,92,3,20,10,0,87,92,3,22,11,0,88,92,3,24,12,0,89,92,
		3,32,16,0,90,92,3,6,3,0,91,77,1,0,0,0,91,78,1,0,0,0,91,79,1,0,0,0,91,80,
		1,0,0,0,91,81,1,0,0,0,91,82,1,0,0,0,91,83,1,0,0,0,91,84,1,0,0,0,91,85,
		1,0,0,0,91,86,1,0,0,0,91,87,1,0,0,0,91,88,1,0,0,0,91,89,1,0,0,0,91,90,
		1,0,0,0,92,5,1,0,0,0,93,94,5,1,0,0,94,95,3,38,19,0,95,7,1,0,0,0,96,97,
		5,9,0,0,97,98,3,64,32,0,98,99,5,2,0,0,99,100,3,38,19,0,100,9,1,0,0,0,101,
		102,3,52,26,0,102,103,5,2,0,0,103,104,3,38,19,0,104,11,1,0,0,0,105,106,
		3,52,26,0,106,107,5,41,0,0,107,108,3,38,19,0,108,13,1,0,0,0,109,110,3,
		52,26,0,110,111,7,0,0,0,111,15,1,0,0,0,112,113,5,10,0,0,113,114,5,26,0,
		0,114,116,3,62,31,0,115,117,3,36,18,0,116,115,1,0,0,0,116,117,1,0,0,0,
		117,118,1,0,0,0,118,119,5,35,0,0,119,120,3,2,1,0,120,121,5,36,0,0,121,
		17,1,0,0,0,122,123,3,52,26,0,123,124,3,60,30,0,124,19,1,0,0,0,125,126,
		5,13,0,0,126,127,5,31,0,0,127,128,3,38,19,0,128,129,5,32,0,0,129,130,5,
		35,0,0,130,131,3,2,1,0,131,132,5,36,0,0,132,21,1,0,0,0,133,134,5,11,0,
		0,134,135,5,31,0,0,135,138,5,26,0,0,136,137,5,2,0,0,137,139,3,38,19,0,
		138,136,1,0,0,0,138,139,1,0,0,0,139,140,1,0,0,0,140,141,5,3,0,0,141,144,
		3,38,19,0,142,143,5,3,0,0,143,145,3,38,19,0,144,142,1,0,0,0,144,145,1,
		0,0,0,145,146,1,0,0,0,146,147,5,32,0,0,147,148,5,35,0,0,148,149,3,2,1,
		0,149,150,5,36,0,0,150,23,1,0,0,0,151,152,5,12,0,0,152,153,5,31,0,0,153,
		154,3,64,32,0,154,155,5,3,0,0,155,156,3,64,32,0,156,157,5,14,0,0,157,158,
		3,38,19,0,158,159,5,32,0,0,159,160,5,35,0,0,160,161,3,2,1,0,161,162,5,
		36,0,0,162,25,1,0,0,0,163,165,5,4,0,0,164,166,3,38,19,0,165,164,1,0,0,
		0,165,166,1,0,0,0,166,27,1,0,0,0,167,168,5,15,0,0,168,29,1,0,0,0,169,170,
		5,16,0,0,170,31,1,0,0,0,171,172,5,17,0,0,172,173,5,31,0,0,173,174,3,38,
		19,0,174,180,5,32,0,0,175,181,3,4,2,0,176,177,5,35,0,0,177,178,3,2,1,0,
		178,179,5,36,0,0,179,181,1,0,0,0,180,175,1,0,0,0,180,176,1,0,0,0,181,183,
		1,0,0,0,182,184,3,34,17,0,183,182,1,0,0,0,183,184,1,0,0,0,184,33,1,0,0,
		0,185,191,5,18,0,0,186,192,3,4,2,0,187,188,5,35,0,0,188,189,3,2,1,0,189,
		190,5,36,0,0,190,192,1,0,0,0,191,186,1,0,0,0,191,187,1,0,0,0,192,35,1,
		0,0,0,193,194,5,28,0,0,194,195,5,26,0,0,195,37,1,0,0,0,196,197,6,19,-1,
		0,197,198,5,31,0,0,198,199,3,38,19,0,199,200,5,32,0,0,200,212,1,0,0,0,
		201,202,5,37,0,0,202,212,3,38,19,16,203,212,5,19,0,0,204,212,5,20,0,0,
		205,212,5,21,0,0,206,212,5,22,0,0,207,212,3,40,20,0,208,212,3,18,9,0,209,
		212,3,52,26,0,210,212,3,50,25,0,211,196,1,0,0,0,211,201,1,0,0,0,211,203,
		1,0,0,0,211,204,1,0,0,0,211,205,1,0,0,0,211,206,1,0,0,0,211,207,1,0,0,
		0,211,208,1,0,0,0,211,209,1,0,0,0,211,210,1,0,0,0,212,239,1,0,0,0,213,
		214,10,15,0,0,214,215,5,5,0,0,215,238,3,38,19,16,216,217,10,14,0,0,217,
		218,5,38,0,0,218,238,3,38,19,15,219,220,10,13,0,0,220,221,5,39,0,0,221,
		238,3,38,19,14,222,223,10,12,0,0,223,224,5,59,0,0,224,238,3,38,19,13,225,
		226,10,11,0,0,226,227,5,60,0,0,227,238,3,38,19,12,228,229,10,10,0,0,229,
		230,5,40,0,0,230,238,3,38,19,11,231,232,10,9,0,0,232,233,5,6,0,0,233,234,
		3,38,19,0,234,235,5,28,0,0,235,236,3,38,19,10,236,238,1,0,0,0,237,213,
		1,0,0,0,237,216,1,0,0,0,237,219,1,0,0,0,237,222,1,0,0,0,237,225,1,0,0,
		0,237,228,1,0,0,0,237,231,1,0,0,0,238,241,1,0,0,0,239,237,1,0,0,0,239,
		240,1,0,0,0,240,39,1,0,0,0,241,239,1,0,0,0,242,245,5,35,0,0,243,246,3,
		42,21,0,244,246,3,44,22,0,245,243,1,0,0,0,245,244,1,0,0,0,245,246,1,0,
		0,0,246,247,1,0,0,0,247,248,5,36,0,0,248,41,1,0,0,0,249,254,3,46,23,0,
		250,251,5,3,0,0,251,253,3,46,23,0,252,250,1,0,0,0,253,256,1,0,0,0,254,
		252,1,0,0,0,254,255,1,0,0,0,255,258,1,0,0,0,256,254,1,0,0,0,257,259,5,
		3,0,0,258,257,1,0,0,0,258,259,1,0,0,0,259,43,1,0,0,0,260,265,3,38,19,0,
		261,262,5,3,0,0,262,264,3,38,19,0,263,261,1,0,0,0,264,267,1,0,0,0,265,
		263,1,0,0,0,265,266,1,0,0,0,266,269,1,0,0,0,267,265,1,0,0,0,268,270,5,
		3,0,0,269,268,1,0,0,0,269,270,1,0,0,0,270,45,1,0,0,0,271,272,3,48,24,0,
		272,273,5,2,0,0,273,274,3,38,19,0,274,47,1,0,0,0,275,278,5,26,0,0,276,
		278,3,38,19,0,277,275,1,0,0,0,277,276,1,0,0,0,278,49,1,0,0,0,279,280,3,
		62,31,0,280,286,5,7,0,0,281,282,5,35,0,0,282,283,3,2,1,0,283,284,5,36,
		0,0,284,287,1,0,0,0,285,287,3,4,2,0,286,281,1,0,0,0,286,285,1,0,0,0,287,
		51,1,0,0,0,288,292,5,26,0,0,289,291,3,54,27,0,290,289,1,0,0,0,291,294,
		1,0,0,0,292,290,1,0,0,0,292,293,1,0,0,0,293,53,1,0,0,0,294,292,1,0,0,0,
		295,299,3,56,28,0,296,299,3,58,29,0,297,299,3,60,30,0,298,295,1,0,0,0,
		298,296,1,0,0,0,298,297,1,0,0,0,299,55,1,0,0,0,300,301,5,8,0,0,301,302,
		5,26,0,0,302,57,1,0,0,0,303,304,5,33,0,0,304,305,3,38,19,0,305,306,5,34,
		0,0,306,59,1,0,0,0,307,316,5,31,0,0,308,313,3,38,19,0,309,310,5,3,0,0,
		310,312,3,38,19,0,311,309,1,0,0,0,312,315,1,0,0,0,313,311,1,0,0,0,313,
		314,1,0,0,0,314,317,1,0,0,0,315,313,1,0,0,0,316,308,1,0,0,0,316,317,1,
		0,0,0,317,318,1,0,0,0,318,319,5,32,0,0,319,61,1,0,0,0,320,329,5,31,0,0,
		321,326,3,64,32,0,322,323,5,3,0,0,323,325,3,64,32,0,324,322,1,0,0,0,325,
		328,1,0,0,0,326,324,1,0,0,0,326,327,1,0,0,0,327,330,1,0,0,0,328,326,1,
		0,0,0,329,321,1,0,0,0,329,330,1,0,0,0,330,331,1,0,0,0,331,332,5,32,0,0,
		332,63,1,0,0,0,333,335,7,1,0,0,334,336,3,36,18,0,335,334,1,0,0,0,335,336,
		1,0,0,0,336,65,1,0,0,0,27,70,74,91,116,138,144,165,180,183,191,211,237,
		239,245,254,258,265,269,277,286,292,298,313,316,326,329,335
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
